package br.com.henrique.config;

import java.text.SimpleDateFormat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Profile;

import br.com.henrique.dto.EmpresaDto;
import br.com.henrique.dto.EstadoDto;
import br.com.henrique.dto.FaixasCEPMicrozonaDto;
import br.com.henrique.dto.FilialDto;
import br.com.henrique.dto.MicrozonaDto;
import br.com.henrique.dto.MunicipioDto;
import br.com.henrique.dto.RotaEntregaDto;
import br.com.henrique.model.FaixasCEPMicrozonaPK;
import br.com.henrique.model.FilialPK;
import br.com.henrique.model.RotaEntregaPK;
import br.com.henrique.service.EmpresaService;
import br.com.henrique.service.EstadoService;
import br.com.henrique.service.FaixasCEPMicrozonaService;
import br.com.henrique.service.FilialService;
import br.com.henrique.service.MicrozonaService;
import br.com.henrique.service.MunicipioService;
import br.com.henrique.service.RotaEntregaService;
 
@Configuration 
@Profile("dev")
public class AutoCargaBanco implements CommandLineRunner {
    
    // private static Logger logger = LoggerFactory.getLogger(AutoCargaBanco.class);
    
    @Autowired
    private EmpresaService empresaService;
    
    @Autowired
    private EstadoService estadoService;    
    
    @Autowired
    private MunicipioService municipioService;  
    
    @Autowired
    private FilialService filialService;       
    
    @Autowired
    private FaixasCEPMicrozonaService faixasCEPMicrozonaService;    
 
    @Autowired
    private MicrozonaService microzonaService;    
    
    @Autowired
    private RotaEntregaService rotaEntregaService;
    
    @Override
    public void run(String...args) throws Exception { 
        
        final SimpleDateFormat formatterDate = new SimpleDateFormat("dd/MM/yyyy");      
        
        // Carga da Tabela: EMPRESA
        EmpresaDto empresa0001 = new EmpresaDto(21, "VIAVAREJO", "33041260094711", formatterDate.parse("25/08/2016"));  // "33.041.260/0947-11"
        empresaService.addEmpresa(empresa0001);
        
        
        // Carga da Tabela: ESTADO        
        EstadoDto estadoAC = new EstadoDto("AC","Acre");
        estadoService.addEstado(estadoAC);
        EstadoDto estadoAL = new EstadoDto("AL","Alagoas");
        estadoService.addEstado(estadoAL);
        EstadoDto estadoAM = new EstadoDto("AM","Amazonas");
        estadoService.addEstado(estadoAM);
        EstadoDto estadoAP = new EstadoDto("AP","Amapa");
        estadoService.addEstado(estadoAP);
        EstadoDto estadoBA = new EstadoDto("BA","Bahia");
        estadoService.addEstado(estadoBA);
        EstadoDto estadoCE = new EstadoDto("CE","Ceara");
        estadoService.addEstado(estadoCE);
        EstadoDto estadoDF = new EstadoDto("DF","Distrito Federal");
        estadoService.addEstado(estadoDF);
        EstadoDto estadoES = new EstadoDto("ES","Espirito Santo");
        estadoService.addEstado(estadoES);
        EstadoDto estadoFN = new EstadoDto("FN","Fernanando de Noronha");
        estadoService.addEstado(estadoFN);
        EstadoDto estadoGO = new EstadoDto("GO","Goias");
        estadoService.addEstado(estadoGO);
        EstadoDto estadoMA = new EstadoDto("MA","Maranhao");
        estadoService.addEstado(estadoMA);
        EstadoDto estadoMG = new EstadoDto("MG","Minas Gerais");
        estadoService.addEstado(estadoMG);
        EstadoDto estadoMS = new EstadoDto("MS","Mato Grosso sul");
        estadoService.addEstado(estadoMS);
        EstadoDto estadoMT = new EstadoDto("MT","Mato Grosso");
        estadoService.addEstado(estadoMT);
        EstadoDto estadoPA = new EstadoDto("PA","Para");
        estadoService.addEstado(estadoPA);
        EstadoDto estadoPB = new EstadoDto("PB","Paraiba");
        estadoService.addEstado(estadoPB);
        EstadoDto estadoPE = new EstadoDto("PE","Pernambuco");
        estadoService.addEstado(estadoPE);
        EstadoDto estadoPI = new EstadoDto("PI","Piaui");
        estadoService.addEstado(estadoPI);
        EstadoDto estadoPR = new EstadoDto("PR","Parana");
        estadoService.addEstado(estadoPR);
        EstadoDto estadoRJ = new EstadoDto("RJ","Rio de Janeiro");
        estadoService.addEstado(estadoRJ);
        EstadoDto estadoRN = new EstadoDto("RN","Rrio Grande do Norte");
        estadoService.addEstado(estadoRN);
        EstadoDto estadoRO = new EstadoDto("RO","Rondonia");
        estadoService.addEstado(estadoRO);
        EstadoDto estadoRR = new EstadoDto("RR","Roraima");
        estadoService.addEstado(estadoRR);
        EstadoDto estadoRS = new EstadoDto("RS","Rio Grande do Sul");
        estadoService.addEstado(estadoRS);
        EstadoDto estadoSC = new EstadoDto("SC","Santa Catarina");
        estadoService.addEstado(estadoSC);
        EstadoDto estadoSE = new EstadoDto("SE","Sergipe");
        estadoService.addEstado(estadoSE);
        EstadoDto estadoSP = new EstadoDto("SP","Sao paulo");
        estadoService.addEstado(estadoSP);
        EstadoDto estadoTO = new EstadoDto("TO","Tocantins");
        estadoService.addEstado(estadoTO);
        
        
        // Carga da Tabela: MUNICIPIO
        // Espirito Santo
        MunicipioDto municipioES27529 = new MunicipioDto(27529, "Afonso claudio", estadoES);
        municipioService.addMunicipio(municipioES27529);
        MunicipioDto municipioES27537 = new MunicipioDto(27537, "Agua doce do no", estadoES);
        municipioService.addMunicipio(municipioES27537);
        MunicipioDto municipioES27545 = new MunicipioDto(27545, "Aguia branca", estadoES);
        municipioService.addMunicipio(municipioES27545);
        MunicipioDto municipioES27553 = new MunicipioDto(27553, "Alegre", estadoES);
        municipioService.addMunicipio(municipioES27553);
        MunicipioDto municipioES27561 = new MunicipioDto(27561, "Alfredo chaves", estadoES);
        municipioService.addMunicipio(municipioES27561);
        MunicipioDto municipioES27570 = new MunicipioDto(27570, "Alto rio novo", estadoES);
        municipioService.addMunicipio(municipioES27570);
        MunicipioDto municipioES27588 = new MunicipioDto(27588, "Anchieta", estadoES);
        municipioService.addMunicipio(municipioES27588);
        MunicipioDto municipioES27596 = new MunicipioDto(27596, "Apiaca", estadoES);
        municipioService.addMunicipio(municipioES27596);
        MunicipioDto municipioES27600 = new MunicipioDto(27600, "Aracruz", estadoES);
        municipioService.addMunicipio(municipioES27600);
        MunicipioDto municipioES27618 = new MunicipioDto(27618, "Atilio vivacqua", estadoES);
        municipioService.addMunicipio(municipioES27618);
        MunicipioDto municipioES27626 = new MunicipioDto(27626, "Baixo guandu", estadoES);
        municipioService.addMunicipio(municipioES27626);
        MunicipioDto municipioES27634 = new MunicipioDto(27634, "Barra sao fco", estadoES);
        municipioService.addMunicipio(municipioES27634);
        MunicipioDto municipioES27642 = new MunicipioDto(27642, "Boa esperanca", estadoES);
        municipioService.addMunicipio(municipioES27642);
        MunicipioDto municipioES27650 = new MunicipioDto(27650, "B.jesus norte", estadoES);
        municipioService.addMunicipio(municipioES27650);
        MunicipioDto municipioES27669 = new MunicipioDto(27669, "Cach.itapemirim", estadoES);
        municipioService.addMunicipio(municipioES27669);
        MunicipioDto municipioES27677 = new MunicipioDto(27677, "Cariacica", estadoES);
        municipioService.addMunicipio(municipioES27677);
        MunicipioDto municipioES27685 = new MunicipioDto(27685, "Castelo", estadoES);
        municipioService.addMunicipio(municipioES27685);
        MunicipioDto municipioES27693 = new MunicipioDto(27693, "Colatina", estadoES);
        municipioService.addMunicipio(municipioES27693);
        MunicipioDto municipioES27707 = new MunicipioDto(27707, "Conc.da barra", estadoES);
        municipioService.addMunicipio(municipioES27707);
        MunicipioDto municipioES27715 = new MunicipioDto(27715, "Conc. castelo", estadoES);
        municipioService.addMunicipio(municipioES27715);
        MunicipioDto municipioES27723 = new MunicipioDto(27723, "Div.s.lourenco", estadoES);
        municipioService.addMunicipio(municipioES27723);
        MunicipioDto municipioES27731 = new MunicipioDto(27731, "Doming. martins", estadoES);
        municipioService.addMunicipio(municipioES27731);
        MunicipioDto municipioES27740 = new MunicipioDto(27740, "Dores rio preto", estadoES);
        municipioService.addMunicipio(municipioES27740);
        MunicipioDto municipioES27758 = new MunicipioDto(27758, "Ecoporanga", estadoES);
        municipioService.addMunicipio(municipioES27758);
        MunicipioDto municipioES27766 = new MunicipioDto(27766, "Fundao", estadoES);
        municipioService.addMunicipio(municipioES27766);
        MunicipioDto municipioES27774 = new MunicipioDto(27774, "Guacui", estadoES);
        municipioService.addMunicipio(municipioES27774);
        MunicipioDto municipioES27782 = new MunicipioDto(27782, "Guarapari", estadoES);
        municipioService.addMunicipio(municipioES27782);
        MunicipioDto municipioES27790 = new MunicipioDto(27790, "Ibatiba", estadoES);
        municipioService.addMunicipio(municipioES27790);
        MunicipioDto municipioES27804 = new MunicipioDto(27804, "Ibiracu", estadoES);
        municipioService.addMunicipio(municipioES27804);
        MunicipioDto municipioES27812 = new MunicipioDto(27812, "Ibitirama", estadoES);
        municipioService.addMunicipio(municipioES27812);
        MunicipioDto municipioES27820 = new MunicipioDto(27820, "Iconha", estadoES);
        municipioService.addMunicipio(municipioES27820);
        MunicipioDto municipioES27839 = new MunicipioDto(27839, "Irupi", estadoES);
        municipioService.addMunicipio(municipioES27839);
        MunicipioDto municipioES27847 = new MunicipioDto(27847, "Itaguacu", estadoES);
        municipioService.addMunicipio(municipioES27847);
        MunicipioDto municipioES27855 = new MunicipioDto(27855, "Itapemirim", estadoES);
        municipioService.addMunicipio(municipioES27855);
        MunicipioDto municipioES27863 = new MunicipioDto(27863, "Itarana", estadoES);
        municipioService.addMunicipio(municipioES27863);
        MunicipioDto municipioES27871 = new MunicipioDto(27871, "Iuna", estadoES);
        municipioService.addMunicipio(municipioES27871);
        MunicipioDto municipioES27880 = new MunicipioDto(27880, "Jaguare", estadoES);
        municipioService.addMunicipio(municipioES27880);
        MunicipioDto municipioES27898 = new MunicipioDto(27898, "Jeron. monteiro", estadoES);
        municipioService.addMunicipio(municipioES27898);
        MunicipioDto municipioES27901 = new MunicipioDto(27901, "Joao neiva", estadoES);
        municipioService.addMunicipio(municipioES27901);
        MunicipioDto municipioES27910 = new MunicipioDto(27910, "Laranja terra", estadoES);
        municipioService.addMunicipio(municipioES27910);
        MunicipioDto municipioES27928 = new MunicipioDto(27928, "Linhares", estadoES);
        municipioService.addMunicipio(municipioES27928);
        MunicipioDto municipioES27936 = new MunicipioDto(27936, "Mantenopolis", estadoES);
        municipioService.addMunicipio(municipioES27936);
        MunicipioDto municipioES27944 = new MunicipioDto(27944, "Marataizes", estadoES);
        municipioService.addMunicipio(municipioES27944);
        MunicipioDto municipioES27952 = new MunicipioDto(27952, "Mchal floriano", estadoES);
        municipioService.addMunicipio(municipioES27952);
        MunicipioDto municipioES27960 = new MunicipioDto(27960, "Marilandia", estadoES);
        municipioService.addMunicipio(municipioES27960);
        MunicipioDto municipioES27979 = new MunicipioDto(27979, "Mimoso do sul", estadoES);
        municipioService.addMunicipio(municipioES27979);
        MunicipioDto municipioES27987 = new MunicipioDto(27987, "Montanha", estadoES);
        municipioService.addMunicipio(municipioES27987);
        MunicipioDto municipioES27995 = new MunicipioDto(27995, "Mucurici", estadoES);
        municipioService.addMunicipio(municipioES27995);
        MunicipioDto municipioES28002 = new MunicipioDto(28002, "Muniz freire", estadoES);
        municipioService.addMunicipio(municipioES28002);
        MunicipioDto municipioES28010 = new MunicipioDto(28010, "Muqui", estadoES);
        municipioService.addMunicipio(municipioES28010);
        MunicipioDto municipioES28029 = new MunicipioDto(28029, "Nova venecia", estadoES);
        municipioService.addMunicipio(municipioES28029);
        MunicipioDto municipioES28037 = new MunicipioDto(28037, "Pancas", estadoES);
        municipioService.addMunicipio(municipioES28037);
        MunicipioDto municipioES28045 = new MunicipioDto(28045, "Pedro canario", estadoES);
        municipioService.addMunicipio(municipioES28045);
        MunicipioDto municipioES28053 = new MunicipioDto(28053, "Pinheiros", estadoES);
        municipioService.addMunicipio(municipioES28053);
        MunicipioDto municipioES28061 = new MunicipioDto(28061, "Piuma", estadoES);
        municipioService.addMunicipio(municipioES28061);
        MunicipioDto municipioES28070 = new MunicipioDto(28070, "Pres.kennedy", estadoES);
        municipioService.addMunicipio(municipioES28070);
        MunicipioDto municipioES28088 = new MunicipioDto(28088, "Rio bananal", estadoES);
        municipioService.addMunicipio(municipioES28088);
        MunicipioDto municipioES28096 = new MunicipioDto(28096, "Rio novo do sul", estadoES);
        municipioService.addMunicipio(municipioES28096);
        MunicipioDto municipioES28100 = new MunicipioDto(28100, "Sta leopoldina", estadoES);
        municipioService.addMunicipio(municipioES28100);
        MunicipioDto municipioES28118 = new MunicipioDto(28118, "Sta m.jetiba", estadoES);
        municipioService.addMunicipio(municipioES28118);
        MunicipioDto municipioES28126 = new MunicipioDto(28126, "Santa teresa", estadoES);
        municipioService.addMunicipio(municipioES28126);
        MunicipioDto municipioES28134 = new MunicipioDto(28134, "S.doming. norte", estadoES);
        municipioService.addMunicipio(municipioES28134);
        MunicipioDto municipioES28142 = new MunicipioDto(28142, "S.gabriel palha", estadoES);
        municipioService.addMunicipio(municipioES28142);
        MunicipioDto municipioES28150 = new MunicipioDto(28150, "S.jose calcado", estadoES);
        municipioService.addMunicipio(municipioES28150);
        MunicipioDto municipioES28169 = new MunicipioDto(28169, "Sao mateus", estadoES);
        municipioService.addMunicipio(municipioES28169);
        MunicipioDto municipioES28177 = new MunicipioDto(28177, "Serra", estadoES);
        municipioService.addMunicipio(municipioES28177);
        MunicipioDto municipioES28185 = new MunicipioDto(28185, "Vargem alta", estadoES);
        municipioService.addMunicipio(municipioES28185);
        MunicipioDto municipioES28193 = new MunicipioDto(28193, "V.nva imigrante", estadoES);
        municipioService.addMunicipio(municipioES28193);
        MunicipioDto municipioES28207 = new MunicipioDto(28207, "Viana", estadoES);
        municipioService.addMunicipio(municipioES28207);
        MunicipioDto municipioES28215 = new MunicipioDto(28215, "Vila pavao", estadoES);
        municipioService.addMunicipio(municipioES28215);
        MunicipioDto municipioES28223 = new MunicipioDto(28223, "Vila velha", estadoES);
        municipioService.addMunicipio(municipioES28223);
        MunicipioDto municipioES28231 = new MunicipioDto(28231, "Vitoria", estadoES);
        municipioService.addMunicipio(municipioES28231);
        MunicipioDto municipioES49867 = new MunicipioDto(49867, "Brejetuba", estadoES);
        municipioService.addMunicipio(municipioES49867);
        MunicipioDto municipioES49875 = new MunicipioDto(49875, "S.roque canaa", estadoES);
        municipioService.addMunicipio(municipioES49875);
        MunicipioDto municipioES49883 = new MunicipioDto(49883, "Vila valerio", estadoES);
        municipioService.addMunicipio(municipioES49883);
        MunicipioDto municipioES52892 = new MunicipioDto(52892, "Sooretama", estadoES);
        municipioService.addMunicipio(municipioES52892);
        MunicipioDto municipioES53040 = new MunicipioDto(53040, "Ponto belo", estadoES);
        municipioService.addMunicipio(municipioES53040);
        MunicipioDto municipioES55425 = new MunicipioDto(55425, "Gov.lindenberg", estadoES);
        municipioService.addMunicipio(municipioES55425);        
        
        // Sao Paulo
        MunicipioDto municipioSP2682 = new MunicipioDto(2682, "Jundiai", estadoSP);
        municipioService.addMunicipio(municipioSP2682);

        
        // Carga da Tabela: FILIAL
        FilialPK filialPK = new FilialPK();
        
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1200);
        FilialDto filial1200 = new FilialDto(filialPK, "Teste Thiago - 1200", "33041260012929", 27669, "29300205");
        filialService.addFilial(filial1200);
        
        // Sao Paulo
//        filialPK.setCodigoEmpresa(21);
//        filialPK.setCodigoFilial(1200);
//        FilialDto filial1200 = new FilialDto(filialPK, "JUNDIAI-CASTANHO", "33041260094711", 2682, "13203850");
//        filialService.addFilial(filial1200);


        // Espirito Santo
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(6);
        FilialDto filial0001 = new FilialDto(filialPK, "CACHOEIRO DE ITAPEMIRIM-ES", "33041260012928", 27669, "29300205");
        filialService.addFilial(filial0001);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(53);
        FilialDto filial0002 = new FilialDto(filialPK, "CENTRO-ES", "33041260019930", 28231, "29010361");
        filialService.addFilial(filial0002);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(123);
        FilialDto filial0003 = new FilialDto(filialPK, "CARIACICA 2 - ES", "33041260017300", 27677, "29146205");
        filialService.addFilial(filial0003);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(132);
        FilialDto filial0004 = new FilialDto(filialPK, "SHOP VITÓRIA-ES", "33041260017059", 28231, "29050420");
        filialService.addFilial(filial0004);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1638);
        FilialDto filial0005 = new FilialDto(filialPK, "SHOP PRAIA DA COSTA-ES", "33041260099438", 28223, "29101950");
        filialService.addFilial(filial0005);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1639);
        FilialDto filial0006 = new FilialDto(filialPK, "VITÓRIA-ES", "33041260099608", 28231, "29010002");
        filialService.addFilial(filial0006);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1640);
        FilialDto filial0007 = new FilialDto(filialPK, "SERRA-JD.LIMOEIRO - DEPOSITO", "33041260099195", 28177, "29168074");
        filialService.addFilial(filial0007);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1641);
        FilialDto filial0008 = new FilialDto(filialPK, "CARIACICA-ES", "33041260098970", 27677, "29146201");
        filialService.addFilial(filial0008);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1642);
        FilialDto filial0009 = new FilialDto(filialPK, "CACHOEIRO DE ITAPEMIRIM 2 - ES", "33041260098890", 27669, "29300792");
        filialService.addFilial(filial0009);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1645);
        FilialDto filial0010 = new FilialDto(filialPK, "GUARAPARI-ES", "33041260099004", 27782, "29215002");
        filialService.addFilial(filial0010);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1646);
        FilialDto filial0011 = new FilialDto(filialPK, "VILA VELHA-ES", "33041260099519", 28223, "29100401");
        filialService.addFilial(filial0011);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1648);
        FilialDto filial0012 = new FilialDto(filialPK, "SERRA-ES", "33041260099357", 28177, "29165130");
        filialService.addFilial(filial0012);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1706);
        FilialDto filial0013 = new FilialDto(filialPK, "SHOP BOULEVARD VILA VELHA - ES", "33041260142708", 28223, "29103800");
        filialService.addFilial(filial0013);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1715);
        FilialDto filial0014 = new FilialDto(filialPK, "SHOP MESTRE ALVARO - ES", "33041260141817", 28177, "29160161");
        filialService.addFilial(filial0014);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1764);
        FilialDto filial0015 = new FilialDto(filialPK, "SHOP MOXUARA -  ES", "33041260150212", 27677, "29145910");
        filialService.addFilial(filial0015);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1772);
        FilialDto filial0016 = new FilialDto(filialPK, "SHOP VILA VELHA - ES", "33041260150050", 28223, "29107900");
        filialService.addFilial(filial0016);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(1949);
        FilialDto filial0018 = new FilialDto(filialPK, "SÃO MATEUS - ES", "33041260051826", 28169, "29930900");
        filialService.addFilial(filial0018);
        filialPK.setCodigoEmpresa(21);
        filialPK.setCodigoFilial(2204);
        FilialDto filial0019 = new FilialDto(filialPK, "GLORIA VILA VELHA - ES", "33041260183498", 28223, "29106405");
        filialService.addFilial(filial0019);
        

        // Carga da Tabela: ROTA DE ENTREGA
        RotaEntregaPK rotaEntregaPK = new RotaEntregaPK();
        rotaEntregaPK.setSiglaEstado("ES");        
        
        rotaEntregaPK.setCodigoRota(1); 
        RotaEntregaDto rotaEntrega1 = new RotaEntregaDto(rotaEntregaPK, "1640_VITORIA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega1);
        rotaEntregaPK.setCodigoRota(2); 
        RotaEntregaDto rotaEntrega2 = new RotaEntregaDto(rotaEntregaPK, "1640_SERRA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega2);
        rotaEntregaPK.setCodigoRota(4); 
        RotaEntregaDto rotaEntrega4 = new RotaEntregaDto(rotaEntregaPK, "1640_VILA VELHA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega4);
        rotaEntregaPK.setCodigoRota(5); 
        RotaEntregaDto rotaEntrega5 = new RotaEntregaDto(rotaEntregaPK, "1640_VILA VELHA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega5);
        rotaEntregaPK.setCodigoRota(6); 
        RotaEntregaDto rotaEntrega6 = new RotaEntregaDto(rotaEntregaPK, "1640_CARIACICA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega6);
        rotaEntregaPK.setCodigoRota(8); 
        RotaEntregaDto rotaEntrega8 = new RotaEntregaDto(rotaEntregaPK, "1640_VIANA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega8);
        rotaEntregaPK.setCodigoRota(9); 
        RotaEntregaDto rotaEntrega9 = new RotaEntregaDto(rotaEntregaPK, "1640_GUARAPARI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega9);
        rotaEntregaPK.setCodigoRota(10); 
        RotaEntregaDto rotaEntrega10 = new RotaEntregaDto(rotaEntregaPK, "1640_ALEGRE_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega10);
        rotaEntregaPK.setCodigoRota(11); 
        RotaEntregaDto rotaEntrega11 = new RotaEntregaDto(rotaEntregaPK, "ATILIO/MIMOSO/MUQUI I/46/47/56", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega11);
        rotaEntregaPK.setCodigoRota(12); 
        RotaEntregaDto rotaEntrega12 = new RotaEntregaDto(rotaEntregaPK, "1640_LINHARES_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega12);
        rotaEntregaPK.setCodigoRota(13); 
        RotaEntregaDto rotaEntrega13 = new RotaEntregaDto(rotaEntregaPK, "1640_SAO MATHEUS_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega13);
        rotaEntregaPK.setCodigoRota(14); 
        RotaEntregaDto rotaEntrega14 = new RotaEntregaDto(rotaEntregaPK, "1640_CACHOEIRO DE ITAPEMIRI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega14);
        rotaEntregaPK.setCodigoRota(16); 
        RotaEntregaDto rotaEntrega16 = new RotaEntregaDto(rotaEntregaPK, "1640_CACHOEIRO DE ITAPEMIRI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega16);
        rotaEntregaPK.setCodigoRota(17); 
        RotaEntregaDto rotaEntrega17 = new RotaEntregaDto(rotaEntregaPK, "S.TEREZA/LEOPOLDINA/M.JETIBA", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega17);
        rotaEntregaPK.setCodigoRota(19); 
        RotaEntregaDto rotaEntrega19 = new RotaEntregaDto(rotaEntregaPK, "CAST/C.CAST/V.ALTA I/51/52/55", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega19);
        rotaEntregaPK.setCodigoRota(20); 
        RotaEntregaDto rotaEntrega20 = new RotaEntregaDto(rotaEntregaPK, "1640_VILA VELHA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega20);
        rotaEntregaPK.setCodigoRota(21); 
        RotaEntregaDto rotaEntrega21 = new RotaEntregaDto(rotaEntregaPK, "1640_VITORIA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega21);
        rotaEntregaPK.setCodigoRota(22); 
        RotaEntregaDto rotaEntrega22 = new RotaEntregaDto(rotaEntregaPK, "D.MARTINS/M.FLORIANO/A.CHAVES", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega22);
        rotaEntregaPK.setCodigoRota(23); 
        RotaEntregaDto rotaEntrega23 = new RotaEntregaDto(rotaEntregaPK, "1640_CARIACICA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega23);
        rotaEntregaPK.setCodigoRota(24); 
        RotaEntregaDto rotaEntrega24 = new RotaEntregaDto(rotaEntregaPK, "1640_GUARAPARI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega24);
        rotaEntregaPK.setCodigoRota(25); 
        RotaEntregaDto rotaEntrega25 = new RotaEntregaDto(rotaEntregaPK, "1640_GUARAPARI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega25);
        rotaEntregaPK.setCodigoRota(26); 
        RotaEntregaDto rotaEntrega26 = new RotaEntregaDto(rotaEntregaPK, "1640_SERRA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega26);
        rotaEntregaPK.setCodigoRota(27); 
        RotaEntregaDto rotaEntrega27 = new RotaEntregaDto(rotaEntregaPK, "REGIOES DE SERRA", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega27);
        rotaEntregaPK.setCodigoRota(28); 
        RotaEntregaDto rotaEntrega28 = new RotaEntregaDto(rotaEntregaPK, "1640_SERRA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega28);
        rotaEntregaPK.setCodigoRota(29); 
        RotaEntregaDto rotaEntrega29 = new RotaEntregaDto(rotaEntregaPK, "1640_CARIACICA_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega29);
        rotaEntregaPK.setCodigoRota(53); 
        RotaEntregaDto rotaEntrega53 = new RotaEntregaDto(rotaEntregaPK, "REGIOES DE LINHARES RURAL", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega53);
        rotaEntregaPK.setCodigoRota(67); 
        RotaEntregaDto rotaEntrega67 = new RotaEntregaDto(rotaEntregaPK, "1640_CACHOEIRO DE ITAPEMIRI_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega67);
        rotaEntregaPK.setCodigoRota(72); 
        RotaEntregaDto rotaEntrega72 = new RotaEntregaDto(rotaEntregaPK, "1640_LINHARES_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega72);
        rotaEntregaPK.setCodigoRota(73); 
        RotaEntregaDto rotaEntrega73 = new RotaEntregaDto(rotaEntregaPK, "1640_LINHARES_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega73);
        rotaEntregaPK.setCodigoRota(75); 
        RotaEntregaDto rotaEntrega75 = new RotaEntregaDto(rotaEntregaPK, "1640_INTERIOR_NP", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega75);
        rotaEntregaPK.setCodigoRota(76); 
        RotaEntregaDto rotaEntrega76 = new RotaEntregaDto(rotaEntregaPK, "MINI HUB LJ1639 VITORIA ES", "A", 21, 1639, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega76);
        rotaEntregaPK.setCodigoRota(77); 
        RotaEntregaDto rotaEntrega77 = new RotaEntregaDto(rotaEntregaPK, "MINI HUB LJ1648 SERRA ES", "A", 21, 1648, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega77);
        rotaEntregaPK.setCodigoRota(79); 
        RotaEntregaDto rotaEntrega79 = new RotaEntregaDto(rotaEntregaPK, "L OUTRAS TRANSP. (LEVE)", "A", 21, 1401, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega79);
        rotaEntregaPK.setCodigoRota(80); 
        RotaEntregaDto rotaEntrega80 = new RotaEntregaDto(rotaEntregaPK, "T OUTRAS TRANSP. (PESADO)", "A", 21, 1401, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega80);
        rotaEntregaPK.setCodigoRota(98); 
        RotaEntregaDto rotaEntrega98 = new RotaEntregaDto(rotaEntregaPK, "REVERSA CORREIOS", "A", 21, 1088, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega98);
        rotaEntregaPK.setCodigoRota(99); 
        RotaEntregaDto rotaEntrega99 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1400, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega99);
        rotaEntregaPK.setCodigoRota(110); 
        RotaEntregaDto rotaEntrega110 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega110);
        rotaEntregaPK.setCodigoRota(111); 
        RotaEntregaDto rotaEntrega111 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega111);
        rotaEntregaPK.setCodigoRota(112); 
        RotaEntregaDto rotaEntrega112 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega112);
        rotaEntregaPK.setCodigoRota(115); 
        RotaEntregaDto rotaEntrega115 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega115);
        rotaEntregaPK.setCodigoRota(117); 
        RotaEntregaDto rotaEntrega117 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega117);
        rotaEntregaPK.setCodigoRota(133); 
        RotaEntregaDto rotaEntrega133 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1400, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega133);
        rotaEntregaPK.setCodigoRota(168); 
        RotaEntregaDto rotaEntrega168 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1400, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega168);
        rotaEntregaPK.setCodigoRota(173); 
        RotaEntregaDto rotaEntrega173 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega173);
        rotaEntregaPK.setCodigoRota(183); 
        RotaEntregaDto rotaEntrega183 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1736, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega183);
        rotaEntregaPK.setCodigoRota(294); 
        RotaEntregaDto rotaEntrega294 = new RotaEntregaDto(rotaEntregaPK, "L OUTRAS TRANSP. LEVE", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega294);
        rotaEntregaPK.setCodigoRota(295); 
        RotaEntregaDto rotaEntrega295 = new RotaEntregaDto(rotaEntregaPK, "T OUTRAS TRANSP. PESADO", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega295);
        rotaEntregaPK.setCodigoRota(296); 
        RotaEntregaDto rotaEntrega296 = new RotaEntregaDto(rotaEntregaPK, "KIT COLETA", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega296);
        rotaEntregaPK.setCodigoRota(297); 
        RotaEntregaDto rotaEntrega297 = new RotaEntregaDto(rotaEntregaPK, "RETIRA NOS CORREIOS", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega297);
        rotaEntregaPK.setCodigoRota(298); 
        RotaEntregaDto rotaEntrega298 = new RotaEntregaDto(rotaEntregaPK, "ENTREGA PELOS CORREIOS", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega298);
        rotaEntregaPK.setCodigoRota(299); 
        RotaEntregaDto rotaEntrega299 = new RotaEntregaDto(rotaEntregaPK, "P - REVERSA CORREIOS", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega299);
        rotaEntregaPK.setCodigoRota(300); 
        RotaEntregaDto rotaEntrega300 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB 1646", "A", 21, 1646, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega300);
        rotaEntregaPK.setCodigoRota(301); 
        RotaEntregaDto rotaEntrega301 = new RotaEntregaDto(rotaEntregaPK, "MINI HUB", "A", 21, 1641, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega301);
        rotaEntregaPK.setCodigoRota(302); 
        RotaEntregaDto rotaEntrega302 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB", "A", 21, 1642, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega302);
        rotaEntregaPK.setCodigoRota(303); 
        RotaEntregaDto rotaEntrega303 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB", "A", 21, 1645, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega303);
        rotaEntregaPK.setCodigoRota(304); 
        RotaEntregaDto rotaEntrega304 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB", "A", 21, 1949, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega304);
        rotaEntregaPK.setCodigoRota(305); 
        RotaEntregaDto rotaEntrega305 = new RotaEntregaDto(rotaEntregaPK, "APIACA S JOSE CALDO D2", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega305);
        rotaEntregaPK.setCodigoRota(306); 
        RotaEntregaDto rotaEntrega306 = new RotaEntregaDto(rotaEntregaPK, "DOMINGOS REGIOES D1", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega306);
        rotaEntregaPK.setCodigoRota(307); 
        RotaEntregaDto rotaEntrega307 = new RotaEntregaDto(rotaEntregaPK, "ARACRUZ REGIOES", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega307);
        rotaEntregaPK.setCodigoRota(308); 
        RotaEntregaDto rotaEntrega308 = new RotaEntregaDto(rotaEntregaPK, "SERRA", "A", 21, 1640, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega308);
        rotaEntregaPK.setCodigoRota(309); 
        RotaEntregaDto rotaEntrega309 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1639, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega309);
        rotaEntregaPK.setCodigoRota(310); 
        RotaEntregaDto rotaEntrega310 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1641, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega310);
        rotaEntregaPK.setCodigoRota(311); 
        RotaEntregaDto rotaEntrega311 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1642, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega311);
        rotaEntregaPK.setCodigoRota(312); 
        RotaEntregaDto rotaEntrega312 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1645, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega312);
        rotaEntregaPK.setCodigoRota(313); 
        RotaEntregaDto rotaEntrega313 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1646, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega313);
        rotaEntregaPK.setCodigoRota(70); 
        RotaEntregaDto rotaEntrega314 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1648, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega314);
        
        rotaEntregaPK.setCodigoRota(71); 
        RotaEntregaDto rotaEntrega315 = new RotaEntregaDto(rotaEntregaPK, "MINIHUB SDD", "A", 21, 1949, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega315);

        rotaEntregaPK.setCodigoRota(316); 
        RotaEntregaDto rotaEntrega316 = new RotaEntregaDto(rotaEntregaPK, "Teste Thiago - Rota", "A", 21, 1200, 0);
        rotaEntregaService.addRotaEntrega(rotaEntrega316);
        
        
        
        // Carga da Tabela: MICROZONA
        MicrozonaDto microzona0001 = new MicrozonaDto(null, "ESPIRITO SANTO-EXCLUSIV CNOVA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 70);
        microzonaService.addMicrozona(microzona0001);
        MicrozonaDto microzona0002 = new MicrozonaDto(null, "REVERSA CORREIOS", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 299);
        microzonaService.addMicrozona(microzona0002);
        MicrozonaDto microzona0003 = new MicrozonaDto(null, "RETIRA NOS CORREIOS", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 297);
        microzonaService.addMicrozona(microzona0003);
        MicrozonaDto microzona0004 = new MicrozonaDto(null, "ENTREGA PELOS CORREIOS", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 298);
        microzonaService.addMicrozona(microzona0004);
        MicrozonaDto microzona0005 = new MicrozonaDto(null, "MINIHUB LJ1639 VITORIA - ES", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 76);
        microzonaService.addMicrozona(microzona0005);
        MicrozonaDto microzona0006 = new MicrozonaDto(null, "ESPIRITO SANTO-EXCLUSIV CNOVA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 70);
        microzonaService.addMicrozona(microzona0006);
        MicrozonaDto microzona0007 = new MicrozonaDto(null, "L OUTRAS TRANSPORTADORA(LEVE)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 294);
        microzonaService.addMicrozona(microzona0007);
        MicrozonaDto microzona0008 = new MicrozonaDto(null, "MINIHUB LJ1648 SERRA ES", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 77);
        microzonaService.addMicrozona(microzona0008);
        MicrozonaDto microzona0009 = new MicrozonaDto(null, "T OUTRAS TRANSP.(PESADO)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28177, 295);
        microzonaService.addMicrozona(microzona0009);
        MicrozonaDto microzona0010 = new MicrozonaDto(null, "ESPIRITO SANTO-EXCLUSIVA CNOVA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 71);
        microzonaService.addMicrozona(microzona0010);
        MicrozonaDto microzona0011 = new MicrozonaDto(null, "MINIHUB 1646", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28223, 300);
        microzonaService.addMicrozona(microzona0011);
        MicrozonaDto microzona0012 = new MicrozonaDto(null, "ESPIRITO SANTO-EXCLUSIVA CNOVA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 71);
        microzonaService.addMicrozona(microzona0012);
        MicrozonaDto microzona0013 = new MicrozonaDto(null, "MINI HUB", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27677, 301);
        microzonaService.addMicrozona(microzona0013);
        MicrozonaDto microzona0014 = new MicrozonaDto(null, "MINIHUB", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27669, 302);
        microzonaService.addMicrozona(microzona0014);
        MicrozonaDto microzona0015 = new MicrozonaDto(null, "MINIHUB", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27782, 303);
        microzonaService.addMicrozona(microzona0015);
        MicrozonaDto microzona0016 = new MicrozonaDto(null, "MINIHUB", "A", "N", "X", "X", "X", "X", "X", " ", estadoES, municipioES28169, 304);
        microzonaService.addMicrozona(microzona0016);
        MicrozonaDto microzona0017 = new MicrozonaDto(null, "MINIHUB SDD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 309);
        microzonaService.addMicrozona(microzona0017);
        MicrozonaDto microzona0018 = new MicrozonaDto(null, "MINIHUB SDD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27677, 310);
        microzonaService.addMicrozona(microzona0018);
        MicrozonaDto microzona0019 = new MicrozonaDto(null, "MINIHUB SDD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27669, 311);
        microzonaService.addMicrozona(microzona0019);
        MicrozonaDto microzona0020 = new MicrozonaDto(null, "MINIHUB SDD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES27782, 312);
        microzonaService.addMicrozona(microzona0020);
        MicrozonaDto microzona0021 = new MicrozonaDto(null, "MINIHUB SDD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28223, 313);
        microzonaService.addMicrozona(microzona0021);
        MicrozonaDto microzona0024 = new MicrozonaDto(null, "CARIACICA", "A", "N", " ", "X", " ", "X", "X", "X", estadoES, municipioES27677, 6);
        microzonaService.addMicrozona(microzona0024);
        MicrozonaDto microzona0025 = new MicrozonaDto(null, "CARIACICA", "A", "N", " ", "X", " ", "X", "X", "X", estadoES, municipioES27677, 29);
        microzonaService.addMicrozona(microzona0025);
        MicrozonaDto microzona0026 = new MicrozonaDto(null, "CARIACICA", "A", "N", " ", "X", " ", "X", "X", "X", estadoES, municipioES27677, 6);
        microzonaService.addMicrozona(microzona0026);
        MicrozonaDto microzona0027 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 5);
        microzonaService.addMicrozona(microzona0027);
        MicrozonaDto microzona0028 = new MicrozonaDto(null, "VILA VELHA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28223, 5);
        microzonaService.addMicrozona(microzona0028);
        MicrozonaDto microzona0029 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 5);
        microzonaService.addMicrozona(microzona0029);
        MicrozonaDto microzona0030 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 5);
        microzonaService.addMicrozona(microzona0030);
        MicrozonaDto microzona0031 = new MicrozonaDto(null, "VILA VELHA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28223, 20);
        microzonaService.addMicrozona(microzona0031);
        MicrozonaDto microzona0032 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 5);
        microzonaService.addMicrozona(microzona0032);
        MicrozonaDto microzona0033 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 4);
        microzonaService.addMicrozona(microzona0033);
        MicrozonaDto microzona0034 = new MicrozonaDto(null, "VILA VELHA", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28223, 4);
        microzonaService.addMicrozona(microzona0034);
        MicrozonaDto microzona0035 = new MicrozonaDto(null, "VILA VELHA", "A", "N", "X", "X", "X", " ", "X", "X", estadoES, municipioES28223, 4);
        microzonaService.addMicrozona(microzona0035);
        MicrozonaDto microzona0036 = new MicrozonaDto(null, "F KIT COLETA", "A", "N", "X", "X", "X", "X", "X", " ", estadoES, municipioES28177, 296);
        microzonaService.addMicrozona(microzona0036);
        MicrozonaDto microzona0037 = new MicrozonaDto(null, "AGUA DOCE DO NORTE -URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27537, 12);
        microzonaService.addMicrozona(microzona0037);
        MicrozonaDto microzona0038 = new MicrozonaDto(null, "AGUA DOCE DO NORTE", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27537, 73);
        microzonaService.addMicrozona(microzona0038);
        MicrozonaDto microzona0039 = new MicrozonaDto(null, "AGUA DOCE DO NORTE -URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27537, 12);
        microzonaService.addMicrozona(microzona0039);
        MicrozonaDto microzona0040 = new MicrozonaDto(null, "AGUIA BRANCA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27545, 12);
        microzonaService.addMicrozona(microzona0040);
        MicrozonaDto microzona0041 = new MicrozonaDto(null, "AGUIA BRANCA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27545, 73);
        microzonaService.addMicrozona(microzona0041);
        MicrozonaDto microzona0042 = new MicrozonaDto(null, "AGUIA BRANCA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27545, 12);
        microzonaService.addMicrozona(microzona0042);
        MicrozonaDto microzona0043 = new MicrozonaDto(null, "ALTO RIO NOVO -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27570, 12);
        microzonaService.addMicrozona(microzona0043);

        MicrozonaDto microzona0044 = new MicrozonaDto(null, "Teste Thiago - Microzona", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27570, 316);
        microzonaService.addMicrozona(microzona0044);

        MicrozonaDto microzona0045 = new MicrozonaDto(null, "ALTO RIO NOVO -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27570, 12);
        microzonaService.addMicrozona(microzona0045);
        MicrozonaDto microzona0046 = new MicrozonaDto(null, "BARRA DE S. FRANCISCO- URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27634, 12);
        microzonaService.addMicrozona(microzona0046);
        MicrozonaDto microzona0047 = new MicrozonaDto(null, "BARRA DE S FRANCISCO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27634, 73);
        microzonaService.addMicrozona(microzona0047);
        MicrozonaDto microzona0048 = new MicrozonaDto(null, "BARRA DE S. FRANCISCO- URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27634, 12);
        microzonaService.addMicrozona(microzona0048);
        MicrozonaDto microzona0049 = new MicrozonaDto(null, "ECOPORANGA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27758, 12);
        microzonaService.addMicrozona(microzona0049);
        MicrozonaDto microzona0050 = new MicrozonaDto(null, "ECOPORANGA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27758, 73);
        microzonaService.addMicrozona(microzona0050);
        MicrozonaDto microzona0051 = new MicrozonaDto(null, "ECOPORANGA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27758, 12);
        microzonaService.addMicrozona(microzona0051);
        MicrozonaDto microzona0052 = new MicrozonaDto(null, "ITAPEMIRIM - ES", "A", "N", " ", " ", " ", "X", " ", " ", estadoES, municipioES27855, 14);
        microzonaService.addMicrozona(microzona0052);
        MicrozonaDto microzona0053 = new MicrozonaDto(null, "ITAPEMIRIM", "A", "N", " ", " ", " ", "X", " ", " ", estadoES, municipioES27855, 14);
        microzonaService.addMicrozona(microzona0053);
        MicrozonaDto microzona0054 = new MicrozonaDto(null, "ITAPEMIRIM - ES", "A", "N", " ", " ", " ", "X", " ", " ", estadoES, municipioES27855, 14);
        microzonaService.addMicrozona(microzona0054);
        MicrozonaDto microzona0055 = new MicrozonaDto(null, "MANTENOPOLIS -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27936, 12);
        microzonaService.addMicrozona(microzona0055);
        MicrozonaDto microzona0056 = new MicrozonaDto(null, "MANTENOPOLIS", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27936, 73);
        microzonaService.addMicrozona(microzona0056);
        MicrozonaDto microzona0057 = new MicrozonaDto(null, "MANTENOPOLIS -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27936, 12);
        microzonaService.addMicrozona(microzona0057);
        MicrozonaDto microzona0058 = new MicrozonaDto(null, "MONTANHA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27987, 12);
        microzonaService.addMicrozona(microzona0058);
        MicrozonaDto microzona0059 = new MicrozonaDto(null, "MONTANHA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27987, 73);
        microzonaService.addMicrozona(microzona0059);
        MicrozonaDto microzona0060 = new MicrozonaDto(null, "MONTANHA -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27987, 12);
        microzonaService.addMicrozona(microzona0060);
        MicrozonaDto microzona0061 = new MicrozonaDto(null, "MUCURICI -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27995, 12);
        microzonaService.addMicrozona(microzona0061);
        MicrozonaDto microzona0062 = new MicrozonaDto(null, "MUCURICI", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27995, 73);
        microzonaService.addMicrozona(microzona0062);
        MicrozonaDto microzona0063 = new MicrozonaDto(null, "MUCURICI -ZONA URBANA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27995, 12);
        microzonaService.addMicrozona(microzona0063);
        MicrozonaDto microzona0064 = new MicrozonaDto(null, "NOVA VENECIA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28029, 12);
        microzonaService.addMicrozona(microzona0064);
        MicrozonaDto microzona0065 = new MicrozonaDto(null, "NOVA VENECIA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28029, 73);
        microzonaService.addMicrozona(microzona0065);
        MicrozonaDto microzona0066 = new MicrozonaDto(null, "NOVA VENECIA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28029, 12);
        microzonaService.addMicrozona(microzona0066);
        MicrozonaDto microzona0067 = new MicrozonaDto(null, "PEDRO CANARIO - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28045, 12);
        microzonaService.addMicrozona(microzona0067);
        MicrozonaDto microzona0068 = new MicrozonaDto(null, "PEDRO CANARIO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28045, 73);
        microzonaService.addMicrozona(microzona0068);
        MicrozonaDto microzona0069 = new MicrozonaDto(null, "PEDRO CANARIO - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28045, 12);
        microzonaService.addMicrozona(microzona0069);
        MicrozonaDto microzona0070 = new MicrozonaDto(null, "PINHEIROS", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28053, 12);
        microzonaService.addMicrozona(microzona0070);
        MicrozonaDto microzona0071 = new MicrozonaDto(null, "PINHEIROS", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28053, 73);
        microzonaService.addMicrozona(microzona0071);
        MicrozonaDto microzona0072 = new MicrozonaDto(null, "PINHEIROS", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28053, 12);
        microzonaService.addMicrozona(microzona0072);
        MicrozonaDto microzona0073 = new MicrozonaDto(null, "PONTO BELO - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES53040, 12);
        microzonaService.addMicrozona(microzona0073);
        MicrozonaDto microzona0074 = new MicrozonaDto(null, "PONTO BELO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES53040, 73);
        microzonaService.addMicrozona(microzona0074);
        MicrozonaDto microzona0075 = new MicrozonaDto(null, "PONTO BELO - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES53040, 12);
        microzonaService.addMicrozona(microzona0075);
        MicrozonaDto microzona0076 = new MicrozonaDto(null, "SÃO DOMINGOS DO NORTE - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28134, 12);
        microzonaService.addMicrozona(microzona0076);
        MicrozonaDto microzona0077 = new MicrozonaDto(null, "SAO DOMINGOS DO NORTE", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28134, 73);
        microzonaService.addMicrozona(microzona0077);
        MicrozonaDto microzona0078 = new MicrozonaDto(null, "SÃO DOMINGOS DO NORTE - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28134, 12);
        microzonaService.addMicrozona(microzona0078);
        MicrozonaDto microzona0079 = new MicrozonaDto(null, "SÃO GABRIEL DA PALHA - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28142, 12);
        microzonaService.addMicrozona(microzona0079);
        MicrozonaDto microzona0080 = new MicrozonaDto(null, "SAO GABRIEL DA PALHA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28142, 73);
        microzonaService.addMicrozona(microzona0080);
        MicrozonaDto microzona0081 = new MicrozonaDto(null, "SÃO GABRIEL DA PALHA - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28142, 12);
        microzonaService.addMicrozona(microzona0081);
        MicrozonaDto microzona0082 = new MicrozonaDto(null, "VILA PAVÃO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28215, 12);
        microzonaService.addMicrozona(microzona0082);
        MicrozonaDto microzona0083 = new MicrozonaDto(null, "VILA PAVAO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28215, 73);
        microzonaService.addMicrozona(microzona0083);
        MicrozonaDto microzona0084 = new MicrozonaDto(null, "VILA PAVÃO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES28215, 12);
        microzonaService.addMicrozona(microzona0084);
        MicrozonaDto microzona0085 = new MicrozonaDto(null, "VILA VALERIO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES49883, 12);
        microzonaService.addMicrozona(microzona0085);
        MicrozonaDto microzona0086 = new MicrozonaDto(null, "VILA VALERIO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES49883, 73);
        microzonaService.addMicrozona(microzona0086);
        MicrozonaDto microzona0087 = new MicrozonaDto(null, "VILA VALERIO", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES49883, 12);
        microzonaService.addMicrozona(microzona0087);
        MicrozonaDto microzona0088 = new MicrozonaDto(null, "CONCEIÇÃO DA BARRA - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27707, 12);
        microzonaService.addMicrozona(microzona0088);
        MicrozonaDto microzona0089 = new MicrozonaDto(null, "CONCEICAO DA BARRA", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27707, 73);
        microzonaService.addMicrozona(microzona0089);
        MicrozonaDto microzona0090 = new MicrozonaDto(null, "CONCEIÇÃO DA BARRA - ES", "A", "N", " ", " ", "X", " ", " ", "X", estadoES, municipioES27707, 12);
        microzonaService.addMicrozona(microzona0090);
        MicrozonaDto microzona0091 = new MicrozonaDto(null, "SAO MATHEUS", "A", "N", " ", "X", " ", " ", " ", " ", estadoES, municipioES28169, 13);
        microzonaService.addMicrozona(microzona0091);
//        MicrozonaDto microzona0106 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 280);
//        microzonaService.addMicrozona(microzona0106);
//        MicrozonaDto microzona0107 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 278);
//        microzonaService.addMicrozona(microzona0107);
//        MicrozonaDto microzona0108 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 278);
//        microzonaService.addMicrozona(microzona0108);
//        MicrozonaDto microzona0109 = new MicrozonaDto(null, "187108NOWLOGOUTRAS TRANSPORTAD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 288);
//        microzonaService.addMicrozona(microzona0109);
//        MicrozonaDto microzona0110 = new MicrozonaDto(null, "187108NOWLOGOUTRAS TRANSPORTAD", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 288);
//        microzonaService.addMicrozona(microzona0110);
//        MicrozonaDto microzona0111 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 276);
//        microzonaService.addMicrozona(microzona0111);
//        MicrozonaDto microzona0112 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 271);
//        microzonaService.addMicrozona(microzona0112);
//        MicrozonaDto microzona0113 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO LEVE", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 271);
//        microzonaService.addMicrozona(microzona0113);
//        MicrozonaDto microzona0114 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 291);
//        microzonaService.addMicrozona(microzona0114);
//        MicrozonaDto microzona0115 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 289);
//        microzonaService.addMicrozona(microzona0115);
//        MicrozonaDto microzona0116 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 289);
//        microzonaService.addMicrozona(microzona0116);
//        MicrozonaDto microzona0117 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 285);
//        microzonaService.addMicrozona(microzona0117);
//        MicrozonaDto microzona0118 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 285);
//        microzonaService.addMicrozona(microzona0118);
//        MicrozonaDto microzona0119 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 283);
//        microzonaService.addMicrozona(microzona0119);
//        MicrozonaDto microzona0120 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 283);
//        microzonaService.addMicrozona(microzona0120);
//        MicrozonaDto microzona0121 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 281);
//        microzonaService.addMicrozona(microzona0121);
//        MicrozonaDto microzona0122 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 279);
//        microzonaService.addMicrozona(microzona0122);
//        MicrozonaDto microzona0123 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 277);
//        microzonaService.addMicrozona(microzona0123);
//        MicrozonaDto microzona0124 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 277);
//        microzonaService.addMicrozona(microzona0124);
//        MicrozonaDto microzona0125 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 275);
//        microzonaService.addMicrozona(microzona0125);
//        MicrozonaDto microzona0126 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 274);
//        microzonaService.addMicrozona(microzona0126);
//        MicrozonaDto microzona0127 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 270);
//        microzonaService.addMicrozona(microzona0127);
//        MicrozonaDto microzona0128 = new MicrozonaDto(null, "85186VVLOGRETIRA RAPIDO PESADO", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 270);
//        microzonaService.addMicrozona(microzona0128);
//        MicrozonaDto microzona0129 = new MicrozonaDto(null, "186317PRIME(ATACADO)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 267);
//        microzonaService.addMicrozona(microzona0129);
//        MicrozonaDto microzona0130 = new MicrozonaDto(null, "186317PRIME(ATACADO)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 267);
//        microzonaService.addMicrozona(microzona0130);
//        MicrozonaDto microzona0131 = new MicrozonaDto(null, "186761NOWLOG(KITCOLETA)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 125);
//        microzonaService.addMicrozona(microzona0131);
//        MicrozonaDto microzona0132 = new MicrozonaDto(null, "5383CORREIOS(REVERSACORREIOS)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 113);
//        microzonaService.addMicrozona(microzona0132);
//        MicrozonaDto microzona0133 = new MicrozonaDto(null, "L OUTRAS TRANSP. (LEVE)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 81);
//        microzonaService.addMicrozona(microzona0133);
//        MicrozonaDto microzona0134 = new MicrozonaDto(null, "L OUTRAS TRANSP. (LEVE)", "A", "S", " ", " ", " ", " ", " ", " ", estadoES, municipioES28231, 81);
//        microzonaService.addMicrozona(microzona0134);

        
        // Carga da Tabela: FAIXAS DE MICROZONA
        FaixasCEPMicrozonaPK faixasCEPMicrozonaPK = new FaixasCEPMicrozonaPK();
          
        faixasCEPMicrozonaPK.setCodigoMicrozona(35);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0001 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29620000, 29620000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0001);
        faixasCEPMicrozonaPK.setCodigoMicrozona(36);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0002 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29690000, 29699000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0002);
        faixasCEPMicrozonaPK.setCodigoMicrozona(37);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0003 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29730000, 29742000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0003);
        faixasCEPMicrozonaPK.setCodigoMicrozona(38);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0004 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29725000, 29728000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0004);
        faixasCEPMicrozonaPK.setCodigoMicrozona(39);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0005 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29750000, 29755000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0005);
        faixasCEPMicrozonaPK.setCodigoMicrozona(40);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0006 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29665000, 29669000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0006);
        faixasCEPMicrozonaPK.setCodigoMicrozona(41);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0007 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29950000, 29957000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0007);
        faixasCEPMicrozonaPK.setCodigoMicrozona(44);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0008 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29927000, 29927000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0008);
        
        faixasCEPMicrozonaPK.setCodigoMicrozona(43);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0009 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29920000, 29925000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0009);

        faixasCEPMicrozonaPK.setCodigoMicrozona(42);
        faixasCEPMicrozonaPK.setCodigoSequencial(1);
        FaixasCEPMicrozonaDto faixasCEPMicrozona0010 = new FaixasCEPMicrozonaDto(faixasCEPMicrozonaPK, 29920000, 29925000);
        faixasCEPMicrozonaService.addFaixasCEPMicrozona(faixasCEPMicrozona0010);

    }
    
}
